```{r message=TRUE, warning=TRUE, include=FALSE}
library(tidyverse)
library(plotly)
```

# Setting up your data science environment {#setup}

Here's a general set of instructions for setting up a development environment that includes GitHub, Anaconda, and RStudio:

1.  First, you'll need to install Git on your computer. Git is a version control system that allows you to track changes in your code and collaborate with other developers. You can download the latest version of Git from the official website: [**https://git-scm.com/downloads**](https://git-scm.com/downloads)

2.  Next, create a GitHub account if you don't already have one. GitHub is a web-based platform for version control and collaboration that uses Git. You can sign up for a free account at [**https://github.com/**](https://github.com/).

3.  Anaconda is a distribution of Python and R that makes it easy to manage dependencies and packages for data science. You can download the latest version of Anaconda from the official website: [**https://www.anaconda.com/products/distribution**](https://www.anaconda.com/products/distribution).

4.  After installing Anaconda, you can create a new environment for your data science project by opening Anaconda Navigator, then click on the Environments tab, and then click on the create button. You can then set the name of the environment, and the version of Python or R you want to use.

5.  Finally, you can install your preferred IDE:

    1.  Spyder IDE is included in your Anaconda installation. You might want to add the [**Notebook plugin**](https://docs.spyder-ide.org/current/plugins/notebook.html){target="_blank"}.

    2.  [**Visual Studio code**](https://code.visualstudio.com/){target="_blank"} with appropriate [**extensions**](https://github.com/microsoft/vscode-jupyter){target="_blank"}.

    3.  Rstudio by downloading the Rstudio installer from [**https://rstudio.com/products/rstudio/download/#download**](https://rstudio.com/products/rstudio/download/#download). RStudio is the editor that you'll use for writing and testing your code.

Below you will find more detailed video instructions on installing and using the different tools in your development environment.

## Working with Git and Github

<iframe width="560" height="315" src="https://www.youtube.com/embed/8Dd7KRpKeaE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/TQN2ZFoGYmI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

## Using Python virtual environments

<iframe width="560" height="315" src="https://www.youtube.com/embed/K7rm_Q5XD8o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/MUZtVEDKXsk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

## Working with Quarto

<iframe width="560" height="315" src="https://www.youtube.com/embed/shVSmYna3GM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>
